# Generated by Django 5.1 on 2024-10-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtask', '0002_taskaddmodel_delete_add_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskaddmodel',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='taskaddmodel',
            name='Priority',
        ),
        migrations.AlterField(
            model_name='taskaddmodel',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='taskaddmodel',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taskaddmodel',
            name='priority',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
